### PR TITLE
[WIP] Integration of the latest `asdl` package

### PR DESCRIPTION
**Pull request by aleximmer**
Enables regression and provides new interface for several methods that need to be synced (corresponds to #44). 
There are two key quantities that require more investigation and tests:
- [ ] regression empirical fisher seems to mismatch our backpack variant (currently failing test)
- [ ] regression fisher with sampling (`stochastic=True`) currently untested

### CODE REVIEW

**Comment by runame** [comment]
When this PR is ready and our backend also supports regression with ASDL, we can also change the default backend to `AsdlGGN`. This avoids issues with quite a few architectures, which are not implemented via a `Squential`, e.g. #92.

**Comment by adamxyang** [comment]
Hi, I'm also interested in the integration with the new ASDL. Does the current branch with the new ASDL work with classification tasks?

**Comment by adamxyang** [comment]
Looks like changing `fisher_maker = get_fisher_maker(self.model, cfg, self.kfac_conv)` to `fisher_maker = get_fisher_maker(self.model, cfg)` in `asdl.py` line 160 makes things work with the classification example.

**Comment by wiseodd** [comment]
Yes, that hotfix should work without any side effects. Let us know if you found any bugs, though!

**Comment by aleximmer** [comment]
@wiseodd you built on these changes for #144, right? Then, let's close this PR. Do you know if the two issues I report above are resolved?

**Comment by wiseodd** [comment]
Yes, should be good. Both are already covered with passing tests in #144. Closing this.

**Pull request closed without merging**
